### ISSUE TITLE
OSError:[Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by I-M-Russell** [nightldj/dehaze_release#7]
Hi, I run your pertained model on:

pytorch: v0.3.0, 
torchvision: v0.2
python: 2.7 
GPU: GeForce GTX 1080Ti. 

From your code I guess it also support running on single GPU. However, when I test the pre-trained model, I meet this error:

`Traceback (most recent call last):
  File "main.py", line 328, in <module>
    te_l,running_time,loading_time=test(0, save_folder)
  File "main.py", line 297, in test
    for bi,(hinputs, ginputs) in enumerate(te_loader):
  File "/home/xxx/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 417, in __iter__
    return DataLoaderIter(self)
  File "/home/xxx/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 234, in __init__
    w.start()
  File "/home/xxx/anaconda2/lib/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/home/xxx/anaconda2/lib/python2.7/multiprocessing/forking.py", line 121, in __init__
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory`

(To avoid #5, adding ` transforms.Resize((460, 620)),`  after line 204.)
How could I solve this problem?

Additionally, the training method (where I reduce gpu to only 1 with id 0, and batch _size 4, test_batch_size 4)

`python main.py --trans-flag in --use-bn in --batch-size 16 --test-batch-size 8 --optm sgd --lr 0.1 --lr-freq 30 --epochs 60 --rec-w 1 --per-w 1  --print-freq 200 --gpuid 0,1,2,3`

occurs problem similarly.

**Comment by I-M-Russell** [comment]
Could you tell me the type of GPU which you used in this task?

**Comment by nightldj** [comment]
Hi 

I run all the experiments in paper with TitanX. 

I just test the training code on a 1080ti GPU with about 12GB memory and it runs fine on my side. My test code is:

CUDA_VISIBLE_DEVICES=2 python main.py --trans-flag none --use-bn in --batch-size 8 --test-batch-size 8 --optm sgd --lr 0.5 --lr-freq 20 --epochs 40 --rec-w 1  --print-freq 200 --gpuid 0

Have you seen similar error messages before for other pytorch code?

**Comment by I-M-Russell** [comment]
Thanks for your reply. I fixed the mistake I've referred by installing Conda and PyTorch again. However, My RAM is 16G and GPU is GTX 1080Ti, and when I run your test code I got 
`Traceback (most recent call last):
  File "main.py", line 338, in <module>
    tr_l, running_time, loading_time = train(epoch)
  File "main.py", line 267, in train
    loss, target = wrap_net(hinputs, ginputs, args.per_w)
  File "/home/xxx/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "main.py", line 174, in forward
    x,p = self.net(img)
  File "/home/xxx/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xxx/dehaze_release-master/my_autoencoder.py", line 137, in forward
    x = self.decs[i](x)
  File "/home/xxx/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xxx/anaconda2/lib/python2.7/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/xxx/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xxx/anaconda2/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 277, in forward
    self.padding, self.dilation, self.groups)
  File "/home/xxx/anaconda2/lib/python2.7/site-packages/torch/nn/functional.py", line 90, in conv2d
    return f(input, weight, bias)
RuntimeError: $ Torch: not enough memory: you tried to allocate 4GB. Buy new RAM! at /opt/conda/conda-bld/pytorch_1512378360668/work/torch/lib/TH/THGeneral.c:246
`
and the environment:

- pytorch: v0.3.0

- torchvision: v0.2.0

- GPU: GTX1080ti x 1

- CUDAToolKit: v8.0

- cudnn: unknown
I keep watch on the usage of RAM and have its peak without over 80%  but the GPU was not allocated during the code running.

**Comment by nightldj** [comment]
Did you correctly install GPU-supported pytorch? Would you run some simple test like these?
https://stackoverflow.com/questions/48152674/how-to-check-if-pytorch-is-using-the-gpu 
https://pytorch.org/tutorials/beginner/former_torchies/tensor_tutorial.html#cuda-tensors

**Comment by I-M-Russell** [comment]
I can run codes in the first URL, and the 2nd URL(pytorch v1.0.0) doesn't match your code(v0.3.0). 
alternatively I use:
`
x=torch.Tensor(10,3)
x1= x.cuda()
x2=x1.cpu()
print type(x1)
print type(x2)
`to verify this. I don't know if it's available. 
it just sames run correctly:
`>>> import torch
>>> x= torch.Tensor(3,10)
>>> x1=x.cuda()
>>> x2=x1.cpu()
>>> print type(x)
<class 'torch.FloatTensor'>
>>> print type(x1)
<class 'torch.cuda.FloatTensor'>
>>> print type(x2)
<class 'torch.FloatTensor'>
>>> `
from the 1st URL:
`>>> import torch
>>> torch.cuda.current_device()
0L
>>> torch.cuda.device(0)
<torch.cuda.device object at 0x7f0b680cec90>
>>> torch.cuda.device_count()
1L
>>> torch.cuda.get_device_name(0)
'GeForce GTX 1080 Ti'
>>> torch.cuda.is_available()
True`

**Comment by I-M-Russell** [comment]
thanks very much. I can run the code after I reduce the batch-size to 4 in the training stage.

**Comment by nightldj** [comment]
Glad to know!
